from __future__ import annotations

from acars_bridge.hoppie.types import MessageType
from acars_bridge.tap.extract import (
    messages_from_gfo_exchange,
    messages_from_hoppie_exchange,
    parse_form_body,
)


def test_parse_form_body():
    form = parse_form_body(b"logon=x&from=BSC612&to=SERVER&type=inforeq&packet=metar+EGLL")
    assert form["from"] == "BSC612"
    assert form["type"] == "inforeq"
    assert form["packet"] == "metar EGLL"


def test_inforeq_exchange_force_prints(fixture_text):
    form = {
        "from": "BSC612",
        "type": "inforeq",
        "packet": "metar EGLL",
    }
    messages, force = messages_from_hoppie_exchange(
        request_form=form,
        response_text=fixture_text("inforeq_metar.txt"),
        callsign_filter="BSC612",
    )
    assert force is True
    assert messages
    assert messages[0].normalized_body.startswith("METAR EGLL\n")
    assert "EGLL" in messages[0].normalized_body


def test_inforeq_keeps_vatatis_station_on_unavailable():
    form = {
        "from": "DLH9911",
        "type": "inforeq",
        "packet": "vatatis EDDF",
    }
    response = "ok {acars info {THIS ATIS IS NOT\nAVAILABLE}}"
    messages, force = messages_from_hoppie_exchange(
        request_form=form,
        response_text=response,
        callsign_filter="DLH9911",
    )
    assert force is True
    assert len(messages) == 1
    assert messages[0].normalized_body == "VATATIS EDDF\nTHIS ATIS IS NOT\nAVAILABLE"


def test_poll_exchange_normal(fixture_text):
    form = {"from": "BSC612", "type": "poll", "packet": ""}
    messages, force = messages_from_hoppie_exchange(
        request_form=form,
        response_text=fixture_text("cpdlc_short.txt"),
        callsign_filter="BSC612",
    )
    assert force is False
    assert messages
    assert messages[0].message_type.value == "cpdlc"


def test_callsign_filter_skips_other_flights(fixture_text):
    form = {"from": "AAA123", "type": "inforeq", "packet": "metar EGLL"}
    messages, force = messages_from_hoppie_exchange(
        request_form=form,
        response_text=fixture_text("inforeq_metar.txt"),
        callsign_filter="BSC612",
    )
    assert messages == []
    assert force is False


def test_ping_ignored():
    messages, force = messages_from_hoppie_exchange(
        request_form={"from": "BSC612", "type": "ping"},
        response_text="ok",
    )
    assert messages == []
    assert force is False


def test_sniffed_info_body_without_form_type(fixture_text):
    messages, force = messages_from_hoppie_exchange(
        request_form={},
        response_text=fixture_text("inforeq_metar.txt"),
        callsign_filter="BSC612",
    )
    assert force is True
    assert messages
    assert messages[0].callsign == "BSC612"


_GFO_ATIS = """
{
  "success": true,
  "messages": [
    "LSZH INFORMATION I AT 1020 ZULU. END OF INFORMATION I"
  ],
  "parsed": [
    {
      "_id": "6a75ba64789b55cfa7f6abc1",
      "to": "GEC8851",
      "from": "SERVER",
      "type": "FLI",
      "message": "LSZH INFORMATION I AT 1020 ZULU. END OF INFORMATION I",
      "content": "LSZH INFORMATION I AT 1020 ZULU. END OF INFORMATION I"
    }
  ]
}
"""


def test_gfo_uplink_atis_prints():
    messages, force = messages_from_gfo_exchange(
        request_path="/api/datalink/uplink",
        response_text=_GFO_ATIS,
        callsign_filter="GEC8851",
    )
    assert force is False
    assert len(messages) == 1
    assert messages[0].callsign == "GEC8851"
    assert messages[0].sender == "SERVER"
    assert messages[0].message_type is MessageType.INFOREQ
    assert "LSZH INFORMATION I" in messages[0].normalized_body


_GFO_ATIS_PMDG = """
{
  "success": true,
  "messages": ["noise"],
  "parsed": [
    {
      "_id": "abc",
      "to": "GEC8851",
      "from": "SERVER",
      "type": "FLI",
      "message": "LSZH INFORMATION J AT 1050 ZULU. QNH 1021 ....GENERATED BY PMDG USING VATSIM DATA ....END OF INFORMATION J"
    }
  ]
}
"""


def test_gfo_strips_pmdg_network_boilerplate():
    for network in ("VATSIM", "IVAO", "PILOTEDGE"):
        payload = _GFO_ATIS_PMDG.replace("VATSIM", network)
        messages, _force = messages_from_gfo_exchange(
            request_path="/api/datalink/uplink",
            response_text=payload,
            callsign_filter="GEC8851",
        )
        assert len(messages) == 1
        body = messages[0].normalized_body
        assert "GENERATED BY PMDG" not in body.upper()
        assert f"{network} DATA" not in body.upper()
        assert "END OF INFORMATION J" in body
        assert "LSZH INFORMATION J" in body


def test_gfo_cpdlc_decodes_data2_for_print():
    payload = """
    {
      "success": true,
      "messages": ["/data2/66/11/NE/UNABLE"],
      "parsed": [{
        "_id": "abc",
        "to": "GEC8851",
        "from": "EDDF",
        "type": "CPDLC",
        "message": "/data2/66/11/NE/UNABLE"
      }]
    }
    """
    messages, _force = messages_from_gfo_exchange(
        request_path="/api/datalink/uplink",
        response_text=payload,
        callsign_filter="GEC8851",
    )
    assert len(messages) == 1
    msg = messages[0]
    assert msg.message_type is MessageType.CPDLC
    assert msg.normalized_body == "UNABLE"
    assert msg.min == 66
    assert msg.mrn == 11
    assert msg.ra == "NE"
    assert "/data2/" not in msg.normalized_body


def test_gfo_cpdlc_multiline_at_breaks():
    payload = """
    {
      "success": true,
      "messages": [],
      "parsed": [{
        "to": "GEC8851",
        "from": "EDDF",
        "type": "CPDLC",
        "message": "/data2/15//WU/CLIMB TO AND MAINTAIN@FL360"
      }]
    }
    """
    messages, _ = messages_from_gfo_exchange(
        request_path="/api/datalink/uplink",
        response_text=payload,
        callsign_filter="GEC8851",
    )
    assert messages[0].normalized_body == "CLIMB TO AND MAINTAIN FL360"


def test_scrub_message_body_pmdg_variants():
    from acars_bridge.hoppie.sanitize import scrub_message_body

    raw = "QNH 1021 ....GENERATED BY PMDG USING IVAO DATA ....END OF INFORMATION J"
    assert scrub_message_body(raw) == "QNH 1021 END OF INFORMATION J"


def test_gfo_downlink_ignored():
    messages, force = messages_from_gfo_exchange(
        request_path="/api/datalink/downlink",
        response_text='{"success":true,"messages":[],"parsed":[]}',
    )
    assert messages == []
    assert force is False


def test_gfo_callsign_filter():
    messages, force = messages_from_gfo_exchange(
        request_path="/api/datalink/uplink",
        response_text=_GFO_ATIS,
        callsign_filter="DLH4MC",
    )
    assert messages == []
    assert force is False


def test_gfo_empty_poll():
    messages, force = messages_from_gfo_exchange(
        request_path="/api/datalink/uplink",
        response_text='{"success":true,"messages":[],"parsed":[]}',
    )
    assert messages == []
