from __future__ import annotations

import re

# PMDG GFO appends e.g. "....GENERATED BY PMDG USING VATSIM DATA ...."
# (also IVAO / other networks). Not useful on a strip.
_PMDG_NETWORK_NOISE = re.compile(
    r"(?:\s*\.{2,}\s*)?GENERATED BY PMDG USING \S+ DATA(?:\s*\.{2,})?",
    re.IGNORECASE,
)


def scrub_message_body(text: str) -> str:
    """Remove vendor boilerplate from ACARS bodies before store/print."""
    cleaned = _PMDG_NETWORK_NOISE.sub(" ", text or "")
    cleaned = re.sub(r"[ \t]{2,}", " ", cleaned)
    cleaned = re.sub(r" *\n *", "\n", cleaned)
    return cleaned.strip()
